const API_BASE="/api";
const state={events:[],filter:"ALL"};
const $=s=>document.querySelector(s);
const esc=v=>String(v==null?"—":v).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const pick=(o,...k)=>{for(const x of k)if(o&&o[x]!=null)return o[x]};
const dir=s=>String(pick(s,"direction","side","signal")||"").toUpperCase();
const hor=s=>String(pick(s,"horizon","mode","profile")||"—").toUpperCase();
const life=s=>String(pick(s,"lifecycle","status")||"").toUpperCase();
const tm=ms=>ms?new Date(Number(ms)).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"}):"—";
function scans(){return state.events.filter(e=>e.event_type==="scan").sort((a,b)=>Number(b.timestamp_ms||0)-Number(a.timestamp_ms||0))}
function latest(rows){const m=new Map();const head=rows[0]?.payload||{};const rotation=Number(head.rotation_id||0);const position=Number(head.queue_position||0);for(const e of rows)for(const x of e.payload?.markets||[]){const p=Number(e.payload?.queue_position||0);const r=Number(e.payload?.rotation_id||0);if(rotation&&(r!==rotation||p>position))continue;const o=m.get(x.asset);if(!o||Number(e.timestamp_ms)>Number(o.timestamp_ms))m.set(x.asset,{...x,timestamp_ms:e.timestamp_ms,rotation_id:r,queue_position:p})}return [...m.values()]}
function active(ms){const out=[];const seen=new Set();for(const m of ms)for(const s of m.setups||[]){const c=s.candidate||s;const d=dir(c);if((d==="LONG"||d==="SHORT")&&(life(s.lifecycle_result)==="ACTIVE"||!s.lifecycle_result)){const key=[m.asset,hor(s.mode),d,JSON.stringify(s.identity||c.identity||{})].join("|");if(seen.has(key))continue;seen.add(key);out.push({asset:m.asset,mode:s.mode,setup:c,lifecycle:s.lifecycle_result,evidence_concepts:s.evidence_concepts||[],decision_action:s.decision_action||""})}}return out}
function conceptSet(s,x){return new Set([...(s.supporting_concepts||[]),...(s.zone_concepts||[]),...(x?.evidence_concepts||[])])}
function evidence(s,x){const c=conceptSet(s,x);const rows=[
["Market Structure",c.has("market_structure.bos")||c.has("market_structure.choch"),c.has("market_structure.bos")?"BOS confirmed":c.has("market_structure.choch")?"CHoCH observed":"Not confirmed"],
["Liquidity",c.has("liquidity.sweep"),c.has("liquidity.sweep")?"Sweep observed":"No confirmed sweep"],
["BOS",c.has("market_structure.bos"),c.has("market_structure.bos")?"Confirmed":"Not confirmed"],
["CHoCH / MSS",c.has("market_structure.choch")||c.has("market_structure.mss"),c.has("market_structure.mss")?"MSS confirmed":c.has("market_structure.choch")?"CHoCH confirmed":"Not confirmed"],
["Order Block",c.has("order_block.bullish")||c.has("order_block.bearish"),c.has("order_block.bullish")?"Bullish OB":c.has("order_block.bearish")?"Bearish OB":"Not present"],
["FVG",c.has("imbalance.fvg"),c.has("imbalance.fvg")?"Active evidence":"Not present"],
["Zone Reaction",c.has("price_action.rejection"),c.has("price_action.rejection")?"Confirmed":"Not confirmed"],
["Volume",c.has("volume.evidence")||c.has("volume.confirmation"),c.has("volume.evidence")||c.has("volume.confirmation")?"Confirming evidence":"No confirming evidence"]];
return rows.map(r=>'<div class="evidence-row"><span>'+esc(r[0])+'</span><b class="'+(r[1]?"yes":"no")+'">'+(r[1]?"✓":"—")+'</b><small>'+esc(r[2])+'</small></div>').join("")}
function setupCard(x){const s=x.setup||{},entry=s.entry_zone||[],targets=s.target_levels||[];const ev=entry.length?entry.map(v=>v.value).join(" — "):"—";const sl=s.invalidation_level?.value??"—";const tp=targets.length?targets.map(v=>v.value).join(" — "):"—";const why=(s.rationale||[]).join(" ");return '<article class="setup '+dir(s).toLowerCase()+'"><div class="setup-top"><div><b>'+esc(x.asset)+'</b><span class="muted">'+esc(hor(x.mode))+'</span></div><strong>'+esc(dir(s))+'</strong></div><div class="analysis"><div class="analysis-title">ANALYSIS</div>'+evidence(s,x)+'</div><div class="levels"><div><small>ENTRY</small><b>'+esc(ev)+'</b></div><div><small>INVALID</small><b>'+esc(sl)+'</b></div><div><small>TP</small><b>'+esc(tp)+'</b></div><div><small>SCENARIO</small><b>'+esc(s.scenario)+'</b></div></div><div class="why"><span>WHY '+esc(dir(s))+'</span><p>'+esc(why||"Current structural evidence supports this setup.")+'</p></div></article>'}
function waitCards(ms){const out=[];for(const m of ms)for(const h of m.horizons||[]){const action=String(h.decision_action||h.decision||"").toUpperCase();if(action==="LONG"||action==="SHORT"||action==="READY")continue;const c=new Set(h.supported_concepts||[]);const checks=[["Liquidity",c.has("liquidity.sweep")],["Market Structure",c.has("market_structure.bos")||c.has("market_structure.choch")],["OB",c.has("order_block.bullish")||c.has("order_block.bearish")],["FVG",c.has("imbalance.fvg")],["Zone Reaction",c.has("price_action.rejection")],["Volume",c.has("volume.evidence")||c.has("volume.confirmation")]];out.push({asset:m.asset,mode:h.mode,action:action||"WAIT",checks:checks,why:(h.setup_reasons||h.decision_reasons||["structural setup is incomplete"])[0]})}return out}
function render(rows){const e=rows[0],p=e?.payload||{},ms=latest(rows),as=active(ms),u=Number(p.universe_size||0),pos=Number(p.queue_position||0),pct=u?Math.min(100,pos/u*100):0;$("#universe").textContent=u||"—";$("#scanned").textContent=u?pos+"/"+u:"—";$("#rotation").textContent=p.rotation_id?"#"+p.rotation_id:"—";$("#currentMarket").textContent=p.markets?.[0]?.asset||"—";const m=p.markets?.[0];$("#currentStatus").textContent=String(m?.diagnostics?.status||"—").toUpperCase()+" · "+(m?.setups||[]).length+" SETUPS";$("#lastScan").textContent=p.scan_number?"#"+p.scan_number:"—";$("#progress").style.width=pct+"%";$("#rotationMeta").textContent=u?pos+" of "+u+" markets · "+Math.round(pct)+"%":"waiting";$("#active").textContent=as.length;const filtered=as.filter(s=>state.filter==="ALL"||hor(s.mode)===state.filter);$("#setups").innerHTML=filtered.length?filtered.map(setupCard).join(""):'<div class="empty">NO ACTIVE SETUPS</div>';const waits=waitCards(ms).filter(s=>state.filter==="ALL"||String(s.mode).toUpperCase()===state.filter);$("#waits").innerHTML=waits.length?waits.slice(0,6).map(w=>'<article class="wait"><div><b>'+esc(w.asset)+'</b><span>'+esc(w.mode)+'</span></div><strong>'+esc(w.action)+'</strong><div class="checks">'+w.checks.map(c=>'<span class="'+(c[1]?"ok":"missing")+'">'+(c[1]?"✓":"—")+' '+esc(c[0])+'</span>').join("")+'</div><p>'+esc(w.why)+'</p></article>').join(""):'<div class="empty">NO WAIT ANALYSIS</div>';const recent=rows.slice(0,8);$("#count").textContent=recent.length+" SCANS";$("#activity").innerHTML=recent.map(e=>{const p=e.payload||{},m=p.markets?.[0],d=m?.diagnostics||{};return '<div class="row"><time>'+tm(e.timestamp_ms)+'</time><b>'+esc(m?.asset)+'</b><span class="'+String(d.status||"").toLowerCase()+'">'+esc(String(d.status||"—").toUpperCase())+'</span><span>'+(m?.setups||[]).length+' setups</span><small>rotation '+esc(p.rotation_id||"—")+' · '+esc(p.queue_position||"—")+'/'+esc(p.universe_size||"—")+'</small></div>'}).join("")}
let refreshInFlight=false;
async function refresh(){
 if(refreshInFlight)return;
 refreshInFlight=true;
 try{const[h,d]=await Promise.all([fetch(API_BASE+"/health?t="+Date.now(),{cache:"no-store"}).then(x=>x.json()),fetch(API_BASE+"/journal/scans?limit=500&t="+Date.now(),{cache:"no-store"}).then(x=>x.json())]);state.events=d.events||[];render(scans());$("#statusText").textContent=h.ok?"LIVE":"DEGRADED";$("#updated").textContent=tm(Date.now())}catch(e){$("#statusText").textContent="OFFLINE";$("#updated").textContent="—"}finally{refreshInFlight=false}}
$("#filters").addEventListener("click",e=>{const f=e.target.dataset.filter;if(!f)return;document.querySelectorAll("#filters button").forEach(b=>b.classList.remove("active"));e.target.classList.add("active");state.filter=f;render(scans())});refresh();setInterval(refresh,3000);